apiVersion: v1
kind: Service
metadata:
  name: jboss-service
  namespace: jboss
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: jboss-http
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: jboss-https
  - port: 9990
    targetPort: 9990
    protocol: TCP
    name: jboss-mgmt
  selector:
    app: jboss-app
  type: LoadBalancer
